### ISSUE TITLE
question about read-only store

### ISSUE THREAD

**Issue by ARES-Z** [voldemort/voldemort#238]
I use build-push job load five records to read-only store, but i can search only two records use StoreClient API . I want to find why i cant find the other record.  What can i do for it?

**Comment by FelixGV** [comment]
Is this on the latest master? Do you think you could provide a sample dataset and unit test that reproduces the error? We'll be glad to fix it if there is indeed such a bug (:

**Comment by ARES-Z** [comment]
Thanks FelixGV, i have used the latest master , and i will put my store.xml and dataset here, but i don't know how to give you my unit test, so i describe how i executed.
* I get the avro file by useing my mapreduce job ,the result file contains key and value like this
```
Obj^A^B^Vavro.schemaÌ^B{"type":"record","name":"test","namespace":"test","doc":"test","fields":[{"name":"fieldkey","type":"string","doc":""},{"name":"fieldvalue","type":"string","doc":""}]}^@<8e>LÎÝ0+zö«Í56^Yìí^O^D>
test0^Ntest1
test1^Ttest2<8e>LÎÝ0+zö«Í56^Yìí^O
```
* Then i execute my build push job create file local file .metadata   ,0_0_0.data,0_0_0.index,1_0_0.data,1_0_0.index
* Finally i can get test1 by key equals test0, but i cant get test2 by test1
store.xml:
```
<store>
    <name>test</name>
    <persistence>read-only</persistence>
    <description>Test store</description>
    <owners>hermoine@hogwarts.edu</owners>
    <routing-strategy>consistent-routing</routing-strategy>
    <routing>client</routing>
    <replication-factor>1</replication-factor>
    <required-reads>1</required-reads>
    <required-writes>1</required-writes>
    <hinted-handoff-strategy>consistent-handoff</hinted-handoff-strategy>
    <key-serializer>
                         <type>avro-generic</type>
                         <schema-info version="0">"string"</schema-info>
    </key-serializer>
    <value-serializer>
                         <type>avro-generic</type>
                         <schema-info version="0">"string"</schema-info>
    </value-serializer>
</store>
  ```
dataset
```
test1
test2
```

**Comment by arunthirupathi** [comment]
What was the conclusion ? Just curious to understand what caused this.

Thanks,
Arun.
