### ISSUE TITLE
Not able to execute on Multinode Cluster, I have configured Voldemort with Chef and Configuration Paramaters are proper, let me know

### ISSUE THREAD

**Issue by hjdesai2** [voldemort/voldemort#248]
INFO Client zone-id [-1] Attempting to get raw store [voldsys$_metadata_version_persistence] 
07-04-2015 14:13:31 PDT build-and-push INFO - WARN Client Zone is not specified. Default to Zone 0. The servers could be in a remote zone
07-04-2015 14:13:31 PDT build-and-push INFO - INFO Client zone-id [-1] Attempting to get raw store [voldsys$_store_quotas] 
07-04-2015 14:13:31 PDT build-and-push INFO - WARN Client Zone is not specified. Default to Zone 0. The servers could be in a remote zone
07-04-2015 14:13:31 PDT build-and-push ERROR - Exception in thread "main" java.lang.reflect.InvocationTargetException
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at java.lang.reflect.Method.invoke(Method.java:483)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at azkaban.jobtype.JavaJobRunnerMain.runMethod(JavaJobRunnerMain.java:176)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at azkaban.jobtype.JavaJobRunnerMain.(JavaJobRunnerMain.java:125)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at azkaban.jobtype.JavaJobRunnerMain.main(JavaJobRunnerMain.java:72)
07-04-2015 14:13:31 PDT build-and-push ERROR - Caused by: java.lang.RuntimeException: Your store definition does not match the store definition that is already in the cluster. Tried to resolve identical schemas between local and remote, but failed. Have: StoreDefinition(name = new-email-result, type = read-only, description = "test store", key-serializer = SerializerDefinition(name = avro-generic-versioned, schema-info = {0={"type":"string","avro.java.string":"String"}}, compression = null), value-serializer = SerializerDefinition(name = avro-generic-versioned, schema-info = {0={"type":"record","name":"Result","namespace":"com.relateiq.realX.email","doc":"* If you are a client, this is the most important object for your real-email needs.\n     *\n     * This is the object created by all implementations of RealEmailAddressClassifier.\n     * Note that it does not have the classification, just granular scores and explanations.\n     *\n     * Almost all non-Hadoop clients should be interested in this object. In the future,\n     * this object will become an internal detail and clients will get a boolean\n     * true/false for real email.","fields":[{"name":"emailAddress","type":{"type":"string","avro.java.string":"String"}},{"name":"explanation","type":{"type":"enum","name":"Explanation","symbols":["IS_REAL","NOT_REAL_BECAUSE_ENTITY_KEY_SAYS_SO","INVALID_EMAIL_ADDRESS","BLACKLISTED_EMAIL_ADDRESS","BLACKLISTED_EMAIL_DOMAIN","EMAIL_ADDRESS_IS_TOO_LONG","DOMAIN_HAS_TOO_MANY_SUB_COMPONENTS","USERNAME_HAS_TOO_MANY_SUB_COMPONENTS","CONTAINS_BLACKLISTED_EMAIL_USER_NAME_WORD","USERNAME_HAS_NO_LETTERS","USERNAME_HAS_TOO_FEW_LETTERS","BLACKLISTED_EMAIL_USER_NAME","EMAIL_LIST","PROMISCUOUS_EMAIL_SENDER","NOT_REAL_DONT_CARE_WHY"]}},{"name":"score","type":"double"}]}}, compression = null), routing = CLIENT, routing-strategy = consistent-routing, replication = 3, required-reads = 1, preferred-reads = 1, required-writes = 1, preferred-writes = 1, view-target = null, value-transformation = null, retention-days = null, throttle-rate = null, zone-replication-factor = null, zone-count-reads = null, zone-count-writes = null, serializer factory = null), hinted-handoff-strategy = null, hint-preflist-size = null, owners = [kedar.doshi@relateiq.com], memory-footprint(MB)0)
07-04-2015 14:13:31 PDT build-and-push ERROR - But expected: StoreDefinition(name = new-email-result, type = bdb, description = null, key-serializer = SerializerDefinition(name = avro-generic-versioned, schema-info = {0={"type":"string","avro.java.string":"String"}}, compression = null), value-serializer = SerializerDefinition(name = avro-generic-versioned, schema-info = {0={"type":"record","name":"Result","namespace":"com.relateiq.realX.email","fields":[{"name":"emailAddress","type":{"type":"string","avro.java.string":"String"}},{"name":"explanation","type":{"type":"enum","name":"Explanation","symbols":["IS_REAL","NOT_REAL_BECAUSE_ENTITY_KEY_SAYS_SO","INVALID_EMAIL_ADDRESS","BLACKLISTED_EMAIL_ADDRESS","BLACKLISTED_EMAIL_DOMAIN","EMAIL_ADDRESS_IS_TOO_LONG","DOMAIN_HAS_TOO_MANY_SUB_COMPONENTS","USERNAME_HAS_TOO_MANY_SUB_COMPONENTS","CONTAINS_BLACKLISTED_EMAIL_USER_NAME_WORD","USERNAME_HAS_NO_LETTERS","USERNAME_HAS_TOO_FEW_LETTERS","BLACKLISTED_EMAIL_USER_NAME","EMAIL_LIST"]}},{"name":"score","type":"double"}]}}, compression = null), routing = CLIENT, routing-strategy = zone-routing, replication = 3, required-reads = 1, preferred-reads = 1, required-writes = 1, preferred-writes = 1, view-target = null, value-transformation = null, retention-days = 7, throttle-rate = null, zone-replication-factor = {0=1, 1=1, 2=1}, zone-count-reads = 0, zone-count-writes = 0, serializer factory = null), hinted-handoff-strategy = PROXIMITY_STRATEGY, hint-preflist-size = null, owners = [], memory-footprint(MB)0)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at voldemort.store.readonly.mr.azkaban.VoldemortBuildAndPushJob.findAndVerifyAvro(VoldemortBuildAndPushJob.java:947)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at voldemort.store.readonly.mr.azkaban.VoldemortBuildAndPushJob.verifyOrAddStoreAvro(VoldemortBuildAndPushJob.java:770)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	at voldemort.store.readonly.mr.azkaban.VoldemortBuildAndPushJob.run(VoldemortBuildAndPushJob.java:271)
07-04-2015 14:13:31 PDT build-and-push ERROR - 	... 7 more

**Comment by arunthirupathi** [comment]
You are overwriting an old store with a new store definition. Voldemort Read Only Build and Push does not have the capability to update the store definition. You should push a store with a new name instead of trying to overwrite the old store.
