### ISSUE TITLE
Read-Only Voldemort (Cluster with 4 nodes and replication factor of 3), Can't fetch keys when queried for a particular partition.

### ISSUE THREAD

**Issue by hjdesai2** [voldemort/voldemort#252]
Hello,

I have setup 4 Node Cluster of Read-Only Voldemort and pushed the data via HDFS and data resides in Voldemort and according to replication factor = 3 the data is replicated across 3 nodes, so my replication group is for Node 0 ( Node 1 and Node 2) , for Node 1 ( Node 2 and Node 3) , for Node 2 ( Node 3 and Node 0), for Node 3 ( Node 0 and Node 1).

Now, The Partitioning for my cluster is as follows:  
Node 0 (0,4,8,12) , Node1 (1,5,9,13), Node 2( 2,6,10,14) and Node 3 (3,7,11,15)

I can fetch-keys from any node by specifying --all-partitions, however when I want to access specific partition, the shell just stucks 
For eg: ./vadmin.sh stream fet-keys --node 3 --url tcp://usw2a-voldemort-a-2-staging.amz.relateiq.com:6666 --partition 0,4,8,12 --store real-email-result  --> This statement after pressing enter key only says "Fetching keys in partitions 0, 4, 8, 12 of real-email-result" and then stucks, however if I specify --all-partitions then it executes. or --partition 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 then also it executes, but for specific partition like 0,4,8,12 fails. 

Can anybody help me on this. ??

Thanks and Regards,
Himay

**Comment by arunthirupathi** [comment]
Can you send your cluster.xml and stores.xml ? Feel free to replace the sensitive information with placeholder 






Sent from Windows Mail





From: Himay Jesal Desai
Sent: ‎Tuesday‎, ‎April‎ ‎21‎, ‎2015 ‎11‎:‎41‎ ‎PM
To: voldemort/voldemort





Hello,

I have setup 4 Node Cluster of Read-Only Voldemort and pushed the data via HDFS and data resides in Voldemort and according to replication factor = 3 the data is replicated across 3 nodes, so my replication group is for Node 0 ( Node 1 and Node 2) , for Node 1 ( Node 2 and Node 3) , for Node 2 ( Node 3 and Node 0), for Node 3 ( Node 0 and Node 1).

Now, The Partitioning for my cluster is as follows:

Node 0 (0,4,8,12) , Node1 (1,5,9,13), Node 2( 2,6,10,14) and Node 3 (3,7,11,15)

I can fetch-keys from any node by specifying --all-partitions, however when I want to access specific partition, the shell just stucks 
For eg: ./vadmin.sh stream fet-keys --node 3 --url tcp://usw2a-voldemort-a-2-staging.amz.relateiq.com:6666 --partition 0,4,8,12 --store real-email-result --> This statement after pressing enter key only says "Fetching keys in partitions 0, 4, 8, 12 of real-email-result" and then stucks, however if I specify --all-partitions then it executes. or --partition 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 then also it executes, but for specific partition like 0,4,8,12 fails. 

Can anybody help me on this. ??

Thanks and Regards,
Himay

**Comment by hjdesai2** [comment]
My Store.xml
<stores>
  <% node[:voldemort][:stores].each do |store| -%>
  <store>
    <name><%= store %></name>
    <persistence>readonly</persistence>
    <routing>client</routing>
    <routing-strategy>consistent-routing</routing-strategy>
    <replication-factor>3</replication-factor>
    <hinted-handoff-strategy>consistent-handoff</hinted-handoff-strategy>
    <required-reads>1</required-reads>
    <required-writes>1</required-writes>
    <retention-days>7</retention-days>
 <key-serializer>
    <type>avro-generic-versioned</type>
    <schema-info version="0">{"type":"string","avro.java.string":"String"}</schema-info>
  </key-serializer>
  <value-serializer>
    <type>avro-generic-versioned</type>
    <schema-info version="0">{"type":"record","name":"Result","namespace":"com.relateiq.realX.email","fields":[{"name":"emailAddress","type":{"type":"string","avro.java.string":"String"}},{"name":"explanation","type":{"type":"enum","name":"Explanation","symbols":["IS_REAL","NOT_REAL_BECAUSE_ENTITY_KEY_SAYS_SO","INVALID_EMAIL_ADDRESS","BLACKLISTED_EMAIL_ADDRESS","BLACKLISTED_EMAIL_DOMAIN","EMAIL_ADDRESS_IS_TOO_LONG","DOMAIN_HAS_TOO_MANY_SUB_COMPONENTS","USERNAME_HAS_TOO_MANY_SUB_COMPONENTS","CONTAINS_BLACKLISTED_EMAIL_USER_NAME_WORD","USERNAME_HAS_NO_LETTERS","USERNAME_HAS_TOO_FEW_LETTERS","BLACKLISTED_EMAIL_USER_NAME","EMAIL_LIST"]}},{"name":"score","type":"double"}]}</schema-info>
  </value-serializer>
</store>
  <% end -%>
</stores>

My Cluster.xml

<cluster>
        <name><%= node[:voldemort][:cluster_name] %></name>
        <server>
                <id>0</id>
                <host><%= node[:voldemort][:host0] %></host>
                <http-port>8081</http-port>
                <socket-port>6666</socket-port>
                <admin-port>6667</admin-port>
                <partitions>0,4,8,12</partitions>
        </server>
        <server>
                <id>1</id>
                <host><%= node[:voldemort][:host1]%></host>
                <http-port>8081</http-port>
                <socket-port>6666</socket-port>
                <admin-port>6667</admin-port>
                <partitions>1,5,9,13</partitions>
        </server>
        <server>
                <id>2</id>
                <host><%= node[:voldemort][:host2] %></host>
                <http-port>8081</http-port>
                <socket-port>6666</socket-port>
                <admin-port>6667</admin-port>
                <partitions> 2,6,10,14</partitions>
        </server>
        <server>
                <id>3</id>
                <host><%= node[:voldemort][:host3] %></host>
                <http-port>8081</http-port>
                <socket-port>6666</socket-port>
                <admin-port>6667</admin-port>
                <partitions>3,7,11,15</partitions>
        </server>
</cluster>

**Comment by arunthirupathi** [comment]
Himay,
         I still could not get time to look into this. Can you use the
older version of the Voldemort Shell voldemort-admin-tool.sh and see if you
were able to  fetch only specific partitions . That will give me one more
data point when I look into this.

Thanks,
Arun.

On Wed, Apr 22, 2015 at 3:02 PM, Himay Jesal Desai <notifications@github.com

**Comment by hjdesai2** [comment]
I guess with old Admin tool it was running and then I tried with new one again and it worked, but the new one takes extra time then old admin tool. Thanks..
