### ISSUE TITLE
How to keep 3 version of data instead of 2 which is by default

### ISSUE THREAD

**Issue by hjdesai2** [voldemort/voldemort#255]
Hello,

I want to keep three versions of my data instead of two which the Voldemort does by default.
Is there any property I can set, so that I can keep one more copy of data.

**Comment by arunthirupathi** [comment]
What type of Store is it ? For read/write voldemort has replication factor
and setting it to 3, will keep 3 copies.

For read-only build and push, you will set the job properties to
replication factor 3.

Thanks,
Arun.

**Comment by hjdesai2** [comment]
Hi Arun, 

I am using read-only and have the replication factor to 3 but I want to have three version folders on each of the 4 nodes of my voldemort cluster. Currently, on each nodes it's only creating two folders[ One Older and Lastest Data], keeping one older version of data and and when I do new push it's creating new version and swapping and linking to the latest folder. 

For example, 
my_store/
      version-134/
         0.data
         0.index
      version-135/
         0.data
         0.index
      latest -> version-135

But I want to keep version 133 too, but Voldemort deletes it.  Keeps Current latest one and old just previous push, I want to keep data for two previous pushes too. Irrespective of Replication Factor.

**Comment by arunthirupathi** [comment]
Voldemort does not support it out of the box. I recommend you making that
parameter configurable in your own private fork. Once you are sure that it
works, you can send us a pull request to merge it upstream.

Thanks,
Arun.

On Fri, Apr 24, 2015 at 5:18 PM, Himay Jesal Desai <notifications@github.com

**Comment by FelixGV** [comment]
I don't think that's accurate @arunthirupathi.

There is the ```readonly.backups``` config which defaults to 1. This is the number of previous versions to keep around besides the active one. You can set this config to 2 in order to keep a total of 3 versions (1 active + 2 backups).

-F

**Comment by arunthirupathi** [comment]
My bad I apologize for responding without checking the code 






Sent from Windows Mail





From: Felix GV
Sent: ‎Friday‎, ‎April‎ ‎24‎, ‎2015 ‎5‎:‎58‎ ‎PM
To: voldemort/voldemort
Cc: ARUNACHALAM THIRUPATHI





I don't think that's accurate @arunthirupathi.

There is the readonly.backups config which defaults to 1. This is the number of previous versions to keep around besides the active one. You can set this config to 2 in order to keep a total of 3 versions (1 active + 2 backups).

-F

**Comment by hjdesai2** [comment]
@FelixGV Thank you for the inputs and @arunthirupathi : Thank you and no worries. It's working fine now.

**Comment by hjdesai2** [comment]
@FelixGV Thanks for responding and giving the solution and @arunthirupathi Thanks, and no worries.
