### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by elad** [voldemort/voldemort#280]
Hey,

1. The "Download Latest" link leads to 1.6.0 whereas it seems the latest is 1.9.17 (https://github.com/voldemort/voldemort/archive/release-1.9.17.zip).

2. The "Download Previous Releases" link along with the download link at the top of Quickstart leads to an empty page on GitHub.

**Comment by arunthirupathi** [comment]
I removed the Download Previous Versions, as it was pointing to versions
more than 3 years old and they are not updated.

I followed the link for the zip and got the right version, 1.9.17

Thanks,
Arun.

**Comment by elad** [comment]
@arunthirupathi I'm sorry, but I'm not following:

```
air:~ elad$ curl -s www.project-voldemort.com/voldemort/ | grep Download
          <li><a href="https://github.com/voldemort/voldemort/archive/release-1.6.0-cutoff.zip">Download Latest</a></li>
          <li><a href="https://github.com/voldemort/voldemort/downloads">Download Previous Releases</a></li>
air:~ elad$ 
```

What am I missing? :)

**Comment by Exide** [comment]
> I removed the Download Previous Versions, as it was pointing to versions
more than 3 years old and they are not updated.

What if I need a version that old? Where do I download older releases?

**Comment by arunthirupathi** [comment]
Ryan, you can always clone the git repository, checkout a branch
(release-<Version>) and build your own. Sorry that it is extra work, but
often we run into issue where people download older releases and open
issues that are old.

Our team of contributors is small and we did not have the time to automate
the process of uploading new releases and keep it up-to date.

Thanks,
Arun.

**Comment by Exide** [comment]
That is unfortunate. I've looked through the branches, releases, and tags and there is nothing for the version I need (0.90).

Thank you for the quick response.

**Comment by singhsiddharth** [comment]
https://github.com/voldemort/voldemort/tree/release-090

**Comment by Exide** [comment]
Thank you. I appreciate the link. I did not notice pre-1.0 releases didn't use a period in the branch name.

**Comment by FelixGV** [comment]
On a side-node @Exide, I would heavily suggest considering doing the upgrade.

There are LOTS of improvements that went in since 0.90 (: ...

**Comment by FelixGV** [comment]
For example, this is what went into the latest release, 1.10 (:

https://engineering.linkedin.com/blog/2015/10/voldemort-1-10-open-source-release

But a lot also went in 1.9 and the others before that (: ...

-F

**Comment by Exide** [comment]
That is definitely part of the plan :)

**Comment by elad** [comment]
This is no longer an issue since the "Download" link leads to the GitHub releases page. Thanks!

**Comment by FelixGV** [comment]
Thanks for the clean up @elad (:

How's it going with Voldemort? Are you up and running now?

**Comment by elad** [comment]
Hey @FelixGV, I'm dusting off my Voldemort notes and will pick up from where I left off. I'll be sure to follow up on the issue I had last time (#290). :)
