### ISSUE TITLE
Rebalancing Throttler sleep time

### ISSUE THREAD

**Issue by mauso** [voldemort/voldemort#291]
Hi 

we try re-balancing data, because we added new node in cluster 2 to 3, when the process is running we have this error every second 

[12:49:24,930 voldemort.utils.EventThrottler] WARN Throttler sleep time (588 ms) exceeds window size (50 ms). This will likely result in not being able to honor the rate limit accurately. [voldemort-admin-server-t18]

we have 3 servers with 5 GB the RAM, Java has 2 GB and server.properties has standar configuration. 

how can solved this error?

**Comment by FelixGV** [comment]
This is actually not a big a deal... We should change the log to debug-level or even remove it.

**Comment by FelixGV** [comment]
I think this was actually a symptom of a genuine issue. Thanks for pointing it out. I changed the ```EventThrottler```'s default setting and things should work correctly now. The change is in 3c6be4b36fb781ceddf6bbb499c777b9e27095bc. Let me know if you still see any issue.
