### ISSUE TITLE
Accessing data ("get") over HTTP?

### ISSUE THREAD

**Issue by elad** [voldemort/voldemort#418]
I recall there was a way to fetch data from Voldemort over HTTP by issuing GET requests. Unfortunately I can't seem to find anything about it... Am I remembering wrong?

FWIW, strictly for my purposes it looks like `ReadOnlyStoreManagementServlet` can help with both fetching values from a read-only store and swapping read-only stores. Although I wonder if it's meant to be used that way since it seems to force a "management" path (`/read-only/mgmt`)...

**Comment by arunthirupathi** [comment]
Voldemort has co-ordinator service, that you can run for HTTP/REST endpoint.

https://engineering.linkedin.com/voldemort/announcing-voldemort-160-open-source-release

https://github.com/voldemort/voldemort/blob/master/bin/voldemort-coordinator.sh

We haven't run this at scale and the performance of the co-ordinator
service will be slower when compared to the java client. But functionality
wise, it should offer read/write.



Thanks,
Arun.

**Comment by elad** [comment]
Super, looks exactly like what I need. A bit unfortunate that keys are base64, but that's peanuts. :) Thanks!

**Comment by elad** [comment]
I'm reopening this because I don't understand how to work with the coordinator yet.

The `curl_samples.txt` file shows a few examples of working with the coordinator. I have a cluster up, and if I connect to it with the voldemort-shell I can get keys from the store. I started the coordinator and when I try accessing it with curl here's what happens:

```shell
[hadoop@<EMR_HOSTNAME> ~]$ curl http://localhost:8080/test1/my_key
Failure: 400 Bad Request. Missing timeout parameter.
[hadoop@<EMR_HOSTNAME> ~]$ curl -H 'X-VOLD-Request-Timeout-ms: 1000' http://localhost:8080/test1/my_key
Failure: 400 Bad Request. Missing origin time parameter.
[hadoop@<EMR_HOSTNAME> ~]$ curl -H 'X-VOLD-Request-Origin-Time-ms: 1000' -H 'X-VOLD-Request-Timeout-ms: 1000' http://localhost:8080/test1/my_key 
curl: (52) Empty reply from server
[hadoop@<EMR_HOSTNAME> ~]$ 
```

Two questions:

  1. Why are these headers required? Why not have some default values for them...?
  2. What am I doing wrong that causes an empty reply from the server for a valid store/key combination? (it doesn't matter if I base64 encode the key or not)

**Comment by elad** [comment]
I'm closing this issue because the REST server doesn't work with read-only stores, and even if it did, the way it works (requires special headers + returns data that requires additional parsing) doesn't fit my needs. I wrote my own tiny Java service instead that has a much simpler API for my needs.
