### ISSUE TITLE
Using Voldemort client as a dependency

### ISSUE THREAD

**Issue by elad** [voldemort/voldemort#428]
Hello,

I'm trying to write a program that uses Voldemort as a dependency. For that purpose I have packaged Voldemort as a Maven module, uploaded it to a private repository, and included it in the project's POM file as follows:

```xml
    <dependencies>
        <dependency>
            <groupId>voldemort</groupId>
            <artifactId>voldemort</artifactId>
            <version>1.10.18</version>
        </dependency>
    </dependencies>
```

I have short test code that I'm using to see if it works:

```java
        String bootstrapUrl = "tcp://localhost:6666";
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setBootstrapUrls(bootstrapUrl)
                .setEnableLazy(false)
                .setRequestFormatType(RequestFormatType.VOLDEMORT_V3);
        SocketStoreClientFactory factory = new SocketStoreClientFactory(clientConfig);
        StoreClient<String, String> client = factory.getStoreClient("test1");
        String key = "foo";
        Versioned<String> vs = client.get(key);
        String value = vs.getValue();
        System.out.println("key: " + key + " value: " + value);
```

When I try to run it, I get this exception:

```
voldemort.xml.MappingException: org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
```

The culprit is this code:

```
    public ClusterMapper() {
        try {
            SchemaFactory e = SchemaFactory.newInstance("http://www.w3.org/2001/XMLSchema");
            StreamSource source = new StreamSource(ClusterMapper.class.getResourceAsStream("cluster.xsd"));
            this.schema = e.newSchema(source);
        } catch (SAXException var3) {
            throw new MappingException(var3);
        }
    }
```

Specifically, the line that uses `cluster.xsd`. Turns out that when called from outside the package, this doesn't work. One way to work around it is perhaps prepending a `/`, another is to go through `getClassLoader()`. Then again there might be some special magic that would also make it work without any code changes.

Thoughts?

**Comment by arunthirupathi** [comment]
Elad,
    I believe I have seen this in the past, where various transitive
dependencies bring different versions of the SAX parser.

I would also suggest you to see, if you can reproduce the exception by
including the dependency on the jar file produced from github repository.

Thanks,
Arun.

**Comment by elad** [comment]
> I believe I have seen this in the past, where various transitive
> dependencies bring different versions of the SAX parser.

I don't think it's got anything to do with the SAX parser in particular. The exception happens because `getResourceAsStream()` returns `null`. Fixing it is a matter of either calling `getClassLoader().getResourceAsStream()` or prepending a slash character to the path passed to the function.

**Comment by arunthirupathi** [comment]
On re reading you may  have difference in the jar in maven.  Can you
compare jar from the github build and maven. I generally do jar xvf and use
meld to compare.

**Comment by arunthirupathi** [comment]
Elad,
       The Part of the code is executed many millions of times and it is
very hard for me to suspect that, it could have issues.

The ClusterMapper class lives in voldemort.xml package and if you look at
the voldemort jar from github it has cluster.xsd and stores.xsd repeated
under the same path.

[PROMPT]$ jar tvf voldemort-1.10.18.jar | grep -i xsd
  1548 Mon Jul 11 19:47:08 PDT 2016 voldemort/xml/cluster.xsd
  5589 Mon Jul 11 19:47:08 PDT 2016 voldemort/xml/stores.xsd
  1548 Mon Jul 11 19:47:10 PDT 2016 voldemort/xml/cluster.xsd
  5589 Mon Jul 11 19:47:10 PDT 2016 voldemort/xml/stores.xsd

Thanks,
Arun.

**Comment by elad** [comment]
@arunthirupathi yeah, I forgot to mirror the path inside the Jar, sorry for the noise!

For future reference, this is needed in `pom.xml` to map resources:

```xml
        <resources>
            <resource>
                <directory>dist/resources/voldemort/xml/</directory>
                <targetPath>voldemort/xml</targetPath>
            </resource>
        </resources>
```

**Comment by arunthirupathi** [comment]
Though this issue might be fixed, I recommend you to diff the jars to see
what is different between maven and gradle builds. Voldemort migrated from
ant to gradle couple of years back and I made sure that during migration, I
understood all the differences in jar.

Thanks,
Arun.
