### ISSUE TITLE
Creating client in embedded mode

### ISSUE THREAD

**Issue by WhiteTrashLord** [voldemort/voldemort#433]
I am testing Voldemor. I want to run it in embedded mode. But I have the problem that I don't know how to create the client. I don't want to connect via TCP because it should be slower. Is there a StoreClientFactory for the embedded mode?

**Comment by FelixGV** [comment]
So you don't need the network stack at all? If that is the case, then you should use Voldemort's storage engine directly (BDB-JE).

**Comment by arunthirupathi** [comment]
What are your requirements ?

As Felix suggests, if you don't want network, then going with Voldemort is a bad choice in my opinion. Just leverage one of the embedded databases and you will be better off. Embedding a voldemort server is going to be tough as it does not have serialization engine.

If you want schema support then you have to pick and choose voldemort layers carefully, bypass the network layer and use the Storage engine layer. This will take some amount of time, especially if you are new to the code base.
