### ISSUE TITLE
Typo in description of Versioned.java

### ISSUE THREAD

**Issue by hkasera** [voldemort/voldemort#475]
I noticed a very minor [typo](https://github.com/voldemort/voldemort/blob/ea37ef67fa7724180608510c6d4237167b78dd63/src/java/voldemort/versioning/Versioned.java#L29) in the description of `Versioned.java`. The description says _"This class **it** bad to use in map"_ instead of _"This class **is** bad to use in map"_

If this is a welcome request, I would like to raise a PR to fix this issue. 

Regards,
Harshita

**Comment by singhsiddharth** [comment]
Thanks for catching that. Please raise a PR.

**Comment by bitti** [comment]
A whole PR for a single character typo? There are a lot of typos I missed in https://github.com/voldemort/voldemort/pull/454, so why not fix some more on this occasion?
