### ISSUE TITLE
Unable to build and run Voldemort on Windows 10

### ISSUE THREAD

**Issue by zsoltkatona** [voldemort/voldemort#485]
I've followed the instructions in the README.md file, but I wasn't able to run the server under Windows 10. When executing bin\voldemort-server.bat config/single_node_cluster, it's missing the Log4J library and when I build the project with "gradlew clean build -x test" instead of "gradlew clean jar" then I get: "Input line is too long".

**Comment by FelixGV** [comment]
Hi @zsoltkatona,

Thanks for the interest. Unfortunately, the bat script was written a while back and I'm pretty sure no one tested it on Win 10 yet. None of the current active maintainers work on Windows, so I'm afraid you're on your own for this one.

If you figure out a way to fix the script, please send a PR. We'll take your word for it and merge it in (:

-F

**Comment by zsoltkatona** [comment]
Thanks for your quick answer, Felix.

Regards, Zsolt
