### ISSUE TITLE
Stuck at Step 2: Start single node cluster

### ISSUE THREAD

**Issue by richylyq** [voldemort/voldemort#496]
finished with Step 1 but encounter the error could not find or load `main class voldemort.server.voldemortServer` when i try the command for starting the single node cluster.

**Comment by Joserbala** [comment]
How did you solve the issue? I'm facing the same problem.

**Comment by richylyq** [comment]
Hi @Joserbala 
this was actually a small R&D project for school so we didn't explore much. Therefore, sorry if i cannot be of much help. You can try the following steps below, feel free to ask more qns when you are in doubt, I'll try my best to help you. Fingers crossed since it's already 1 year plus haha

clone from this repo
`https://github.com/voldemort/voldemort.git`
use this command to build the project
`./gradlew clean build -x test`
start the server using:
`bin/voldemort-server.bat config/single_node_cluster`
Open up powershell to connect
`bin/voldemort-shell.bat test tcp://localhost:6666/`

**Comment by Joserbala** [comment]
Hi @richylyq
Thanks for replying, I'm actually doing it for a college project. I didn't manage to boot it up on Windows, but in Ubuntu, after following this [tutorial](https://youtu.be/xPg46OBXJFk), it worked. I'll continue investigating why it doesn't function on Windows. My suspicions are towards the Java version.

**Comment by richylyq** [comment]
> Hi @richylyq
> Thanks for replying, I'm actually doing it for a college project. I didn't manage to boot it up on Windows, but in Ubuntu, after following this [tutorial](https://youtu.be/xPg46OBXJFk), it worked. I'll continue investigating why it doesn't function on Windows. My suspicions are towards the Java version.

Hi @Joserbala 
I bet we won't be touching this if not for our school project. How's the investigation going?

**Comment by bitti** [comment]
LinkedIn abandoned this project a few years back, so it's basically unsupported. If you like figuring things out in a context of a school project then you can still have a lot of fun with Voldemort. If you're on a deadline and want results quickly it would be probably better to try out a project with an active community.

**Comment by richylyq** [comment]
> LinkedIn abandoned this project a few years back, so it's basically unsupported. If you like figuring things out in a context of a school project then you can still have a lot of fun with Voldemort. If you're on a deadline and want results quickly it would be probably better to try out a project with an active community.

Most of us that are trying or have tried using Voldemort, were tasked by our professor to do research on it, so we have no say on trying a project with an active community... ><lll 
We can only try to support each other when the need arises

> When Life gives you Lemons, you swallow them whole and carry on with life.

**Comment by Joserbala** [comment]
> LinkedIn abandoned this project a few years back, so it's basically unsupported. If you like figuring things out in a context of a school project then you can still have a lot of fun with Voldemort. If you're on a deadline and want results quickly it would be probably better to try out a project with an active community.

Oh, nice to know! I thought it was so stable that it didn't receive any update since 2017, fool of me... But like you said, it's pretty interesting!

> Hi @Joserbala
> I bet we won't be touching this if not for our school project. How's the investigation going?

Nothing :( I tried updating gradle and configuring Java but it didn't work. I will use it on Ubuntu!

**Comment by bitti** [comment]
Yes, I wouldn't recommend trying to run it on Windows. I think even in it's best times the support on Windows was always inferior.

**Comment by richylyq** [comment]
Hey @Joserbala 
Ubuntu FTW in this kind of life-threatening scenario! HAHA.

I think for me now is the issue of address already in use. I will try to debug when i am free and update here. 

> Nothing :( I tried updating gradle and configuring Java but it didn't work. I will use it on Ubuntu!

Would you mind explaining what issues you face after configuring Java?

**Comment by Joserbala** [comment]
In Windows I still have the same issue that you described in the original comment when I execute `./bin/voldemort-server.sh config/single_node_cluster`, maybe I didn't configure Java well. Do not worry, I will use Ubuntu instead.

**Comment by richylyq** [comment]
Good News. I am able to run Voldemort on Windows 10. I made some changes to the cluster.xml file as idk for some god knows why reason, my port 6666 has already been binded HAHA. 
Steps to be done (Just leaving it here so others can refer in near future). 
1. Download Java SE Development Kit 8u241 and remember to add  in the JDK file path at the  JAVA_HOME variable in system environment.
2. build the project with the command
`./gradlew clean build -x test`
3. start the server using
`bin/voldemort-server.bat config/single_node_cluster`
4. connect via
`bin/voldemort-shell.bat test tcp://localhost:6666/`

**Comment by Joserbala** [comment]
@richylyq thank you!
The problem I had was that I was executing the .sh file instead of the .bat file. Thank you so much!

**Comment by richylyq** [comment]
@Joserbala (╯°□°）╯︵ ┻━┻
